// modules/signals/agency-signals.ts · net-new signals from the demand-driven
// rework (reachability, tech/DOM, comparative reviews, ads, SERP, expert/
// compliance, freshness). Merged into the registry in `registry.ts`. These
// extend the existing 8 categories — no new category (per signal-engineering).

import {
  BOOLEAN_COMPARATORS,
  ENUM_COMPARATORS,
  NUMERIC_COMPARATORS,
  STRING_COMPARATORS,
} from "./comparators";
import type { SignalDefinition } from "./types";

export const agencySignals: readonly SignalDefinition[] = [
  // ── Reachability / contacts (profile) ──────────────────────────────────────
  {
    key: "is_reachable",
    label: "Reachable (any channel)",
    helpTooltip:
      "Has at least one usable contact (email, phone, or social). Unreachable businesses are hidden by default — enriching them wastes spend.",
    category: "profile",
    type: "boolean",
    comparators: BOOLEAN_COMPARATORS,
    defaultValue: true,
    source: "computed-from-contacts",
    cadence: "on-demand",
    column: "Business.reachableChannelCount",
  },
  {
    key: "reachability",
    label: "Reachability",
    helpTooltip:
      "Contact richness: UNREACHABLE / EMAIL_ONLY / PHONE_ONLY / MULTI / RICH.",
    category: "profile",
    type: "enum",
    comparators: ENUM_COMPARATORS,
    enumValues: [
      "UNREACHABLE",
      "EMAIL_ONLY",
      "PHONE_ONLY",
      "MULTI",
      "RICH",
      "UNKNOWN",
    ],
    defaultValue: "RICH",
    source: "computed-from-contacts",
    cadence: "on-demand",
    column: "Business.reachability",
  },
  {
    key: "email_count",
    label: "Emails found",
    helpTooltip: "Distinct emails captured for this business.",
    category: "profile",
    type: "numeric",
    comparators: NUMERIC_COMPARATORS,
    valueUnit: "emails",
    defaultValue: 1,
    source: "computed-from-contacts",
    cadence: "on-demand",
    column: "Contact.value",
  },
  {
    key: "phone_count",
    label: "Phone numbers found",
    helpTooltip: "Distinct phone/WhatsApp numbers captured.",
    category: "profile",
    type: "numeric",
    comparators: NUMERIC_COMPARATORS,
    valueUnit: "phones",
    defaultValue: 1,
    source: "computed-from-contacts",
    cadence: "on-demand",
    column: "Contact.value",
  },
  {
    key: "has_owner_contact",
    label: "Owner/personal contact",
    helpTooltip: "A contact tagged owner or personal (not a generic inbox).",
    category: "profile",
    type: "boolean",
    comparators: BOOLEAN_COMPARATORS,
    defaultValue: true,
    source: "computed-from-contacts",
    cadence: "on-demand",
    column: "Contact.role",
  },
  {
    key: "social_channel_count",
    label: "Social profiles",
    helpTooltip: "Distinct social channels (IG/FB/LinkedIn/TikTok/etc.) found.",
    category: "profile",
    type: "numeric",
    comparators: NUMERIC_COMPARATORS,
    valueUnit: "channels",
    defaultValue: 2,
    source: "computed-from-contacts",
    cadence: "on-demand",
    column: "Contact.channel",
  },
  {
    key: "phone_only",
    label: "Phone-only (no website)",
    helpTooltip:
      "Has a phone but no website — a prime target to pitch a website build.",
    category: "profile",
    type: "boolean",
    comparators: BOOLEAN_COMPARATORS,
    defaultValue: true,
    source: "dataforseo:maps",
    cadence: "weekly",
    column: "Business.website",
  },
  {
    key: "is_hidden",
    label: "Hidden / unreachable",
    helpTooltip:
      "Removed from the working list (no contact channel found). Toggle on to see why each was hidden.",
    category: "exclusions",
    type: "boolean",
    comparators: BOOLEAN_COMPARATORS,
    defaultValue: false,
    source: "computed-from-contacts",
    cadence: "on-demand",
    column: "Business.isHidden",
    isExclusion: true,
  },
  // ── Tech / DOM (website) ────────────────────────────────────────────────────
  {
    key: "cms_platform",
    label: "Website platform",
    helpTooltip:
      "CMS/builder detected from the site (WordPress, Wix, Squarespace, Shopify…). DIY builders are an upsell signal.",
    category: "website",
    type: "string",
    comparators: STRING_COMPARATORS,
    defaultValue: "",
    source: "tech-fingerprint",
    cadence: "on-demand",
    column: "BusinessTech.name",
  },
  {
    key: "has_booking_widget",
    label: "Online booking tool",
    helpTooltip:
      "A booking tool (Calendly/Acuity/Vagaro/Mindbody…) detected on the site. False = a target for a booking-SaaS pitch.",
    category: "website",
    type: "boolean",
    comparators: BOOLEAN_COMPARATORS,
    defaultValue: false,
    source: "tech-fingerprint",
    cadence: "on-demand",
    column: "BusinessTech.category",
  },
  {
    key: "has_analytics",
    label: "Analytics installed",
    helpTooltip: "GA4/GTM/Plausible detected. False = flying blind on traffic.",
    category: "website",
    type: "boolean",
    comparators: BOOLEAN_COMPARATORS,
    defaultValue: false,
    source: "tech-fingerprint",
    cadence: "on-demand",
    column: "BusinessTech.category",
  },
  {
    key: "has_meta_pixel",
    label: "Meta Pixel installed",
    helpTooltip: "Meta (Facebook) Pixel detected on the site.",
    category: "website",
    type: "boolean",
    comparators: BOOLEAN_COMPARATORS,
    defaultValue: false,
    source: "tech-fingerprint",
    cadence: "on-demand",
    column: "BusinessTech.category",
  },
  {
    key: "ads_without_pixel",
    label: "Runs ads, no pixel",
    helpTooltip:
      "Running Meta ads but no Meta Pixel on-site — spending blind. Uniquely detectable because we hold both ad-library + tech data.",
    category: "website",
    type: "boolean",
    comparators: BOOLEAN_COMPARATORS,
    defaultValue: true,
    source: "computed-from-snapshots",
    cadence: "on-demand",
    column: "BusinessTech.category",
  },
  {
    key: "perf_savings_ms",
    label: "Speed-fix headroom",
    helpTooltip:
      "Total millisecond savings from Lighthouse opportunities — a concrete 'we can make your site Xs faster' pitch.",
    category: "website",
    type: "numeric",
    comparators: NUMERIC_COMPARATORS,
    valueUnit: "ms",
    defaultValue: 2000,
    source: "dataforseo:lighthouse",
    cadence: "on-demand",
    column: "LighthouseAudit.perfSavingsMs",
  },
  {
    key: "a11y_violations",
    label: "Accessibility violations",
    helpTooltip:
      "Count of serious Lighthouse a11y failures (alt-text, labels, contrast…) — the exact ones cited in ADA web lawsuits.",
    category: "website",
    type: "numeric",
    comparators: NUMERIC_COMPARATORS,
    valueUnit: "violations",
    defaultValue: 5,
    source: "dataforseo:lighthouse",
    cadence: "on-demand",
    column: "LighthouseAudit.a11yViolationCount",
  },
  {
    key: "no_https",
    label: "No HTTPS",
    helpTooltip: "Site not served over HTTPS — a trust + security gap.",
    category: "website",
    type: "boolean",
    comparators: BOOLEAN_COMPARATORS,
    defaultValue: true,
    source: "dataforseo:lighthouse",
    cadence: "on-demand",
    column: "LighthouseAudit.isOnHttps",
  },
  // ── Comparative reviews ─────────────────────────────────────────────────────
  {
    key: "review_lifecycle",
    label: "Review lifecycle",
    helpTooltip:
      "TRENDING / STABLE / DYING / DORMANT — reputation momentum vs its own history.",
    category: "reviews",
    type: "enum",
    comparators: ENUM_COMPARATORS,
    enumValues: ["TRENDING", "STABLE", "DYING", "DORMANT", "NONE"],
    defaultValue: "DYING",
    source: "computed-from-reviews",
    cadence: "on-demand",
    column: "BusinessSnapshot.reviewLifecycle",
  },
  {
    key: "reviews_vs_cell_pct",
    label: "Reviews vs cell (percentile)",
    helpTooltip:
      "Where this business's review count ranks among peers in the same metro × category. 20 = bottom quintile.",
    category: "reviews",
    type: "numeric",
    comparators: NUMERIC_COMPARATORS,
    valueUnit: "pct",
    defaultValue: 25,
    source: "computed-from-snapshots",
    cadence: "on-demand",
    column: "BusinessSnapshot.msiPercentile",
  },
  {
    key: "stale_no_reviews",
    label: "No reviews recently",
    helpTooltip: "No new review for ~4 months — a fading-reputation lead.",
    category: "reviews",
    type: "boolean",
    comparators: BOOLEAN_COMPARATORS,
    defaultValue: true,
    source: "computed-from-reviews",
    cadence: "on-demand",
    column: "Business.lastReviewAt",
  },
  // ── Ads ─────────────────────────────────────────────────────────────────────
  {
    key: "meta_ad_format_video",
    label: "Runs video ads",
    helpTooltip: "At least one active Meta ad uses a video creative.",
    category: "ads",
    type: "boolean",
    comparators: BOOLEAN_COMPARATORS,
    defaultValue: true,
    source: "meta-ad-library",
    cadence: "monthly",
    column: "AdLibraryEntry.displayFormat",
  },
  {
    key: "ad_market_prevalence",
    label: "Advertisers in cell",
    helpTooltip:
      "How many businesses advertise in this metro × category — high prevalence = competitive ad market.",
    category: "ads",
    type: "numeric",
    comparators: NUMERIC_COMPARATORS,
    valueUnit: "advertisers",
    defaultValue: 5,
    source: "meta-ad-library",
    cadence: "monthly",
    column: "AdMarketRun.advertiserCount",
  },
  // ── Search ──────────────────────────────────────────────────────────────────
  {
    key: "organic_traffic_est",
    label: "Estimated organic visits/mo",
    helpTooltip:
      "Estimated monthly organic visits (DfS etv). Under 50 ≈ near-invisible in search.",
    category: "search",
    type: "numeric",
    comparators: NUMERIC_COMPARATORS,
    valueUnit: "visits",
    defaultValue: 50,
    source: "dataforseo:serp",
    cadence: "monthly",
    column: "BusinessKeyword.latestEstMonthlyVisits",
  },
  // ── Expert / compliance (competitive) ───────────────────────────────────────
  {
    key: "hipaa_pixel_risk",
    label: "HIPAA pixel exposure",
    helpTooltip:
      "Health business with a tracking pixel on a patient-data page — a potential privacy exposure worth checking (legal landscape evolving).",
    category: "competitive",
    type: "boolean",
    comparators: BOOLEAN_COMPARATORS,
    defaultValue: true,
    source: "playbook",
    cadence: "on-demand",
    column: "PlaybookFinding.signalKey",
  },
  {
    key: "ada_risk",
    label: "ADA lawsuit risk",
    helpTooltip:
      "Web-accessibility risk tier from Lighthouse a11y failures — high = the failure classes cited in most 2025 ADA suits.",
    category: "competitive",
    type: "enum",
    comparators: ENUM_COMPARATORS,
    enumValues: ["high", "medium", "low"],
    defaultValue: "high",
    source: "playbook",
    cadence: "on-demand",
    column: "PlaybookFinding.confidence",
  },
  {
    key: "compliance_gap",
    label: "Compliance gap flag",
    helpTooltip:
      "A category-specific compliance gap detected (e.g. missing medical-director disclosure). Shown as evidence, never an accusation.",
    category: "competitive",
    type: "string",
    comparators: STRING_COMPARATORS,
    defaultValue: "",
    source: "playbook",
    cadence: "on-demand",
    column: "Business.complianceFlags",
  },
  {
    key: "license_status",
    label: "License status",
    helpTooltip:
      "State-board license status where covered: ACTIVE / EXPIRED / NOT_FOUND.",
    category: "competitive",
    type: "enum",
    comparators: ENUM_COMPARATORS,
    enumValues: ["ACTIVE", "EXPIRED", "REVOKED", "NOT_FOUND"],
    defaultValue: "NOT_FOUND",
    source: "internal",
    cadence: "on-demand",
    column: "BusinessLicense.status",
  },
  // ── Freshness / discovery (qualifiers) ──────────────────────────────────────
  {
    key: "open_status",
    label: "Operating status",
    helpTooltip: "OPEN / TEMPORARILY_CLOSED / CLOSED_FOREVER from Google.",
    category: "qualifiers",
    type: "enum",
    comparators: ENUM_COMPARATORS,
    enumValues: ["OPEN", "TEMPORARILY_CLOSED", "CLOSED_FOREVER", "UNKNOWN"],
    defaultValue: "OPEN",
    source: "dataforseo:maps",
    cadence: "weekly",
    column: "Business.openStatus",
  },
  {
    key: "data_freshness_days",
    label: "Data freshness (days)",
    helpTooltip:
      "Days since this lead was last refreshed. Filter to only fresh leads — something Apollo can't express.",
    category: "qualifiers",
    type: "numeric",
    comparators: NUMERIC_COMPARATORS,
    valueUnit: "days",
    defaultValue: 30,
    source: "internal",
    cadence: "on-demand",
    column: "Business.lastRefreshedAt",
  },
  {
    key: "metro",
    label: "Metro area",
    helpTooltip: "The consolidated metro this business is grouped into.",
    category: "qualifiers",
    type: "string",
    comparators: STRING_COMPARATORS,
    defaultValue: "",
    source: "internal",
    cadence: "static",
    column: "Business.metroSlug",
  },
];
