// lib/geo/places.generated.ts · GENERATED — do not edit by hand.
//
// Produced by `pnpm tsx scripts/build-places-gazetteer.ts` from the GeoNames
// `cities15000` dataset (US + Canada, population ≥ 100,000),
// deduped against the curated majors in us-metros.ts. Re-run to refresh.
//
// Source: https://download.geonames.org/export/dump/cities15000.zip (CC-BY 4.0)
// Counts: 291 cities (220 US · 71 CA). Every coordinate is real
// GeoNames data; discovery searches DfS by coordinate (US+CA fully covered).

import type { UsMetro } from "./us-metros";

export const GENERATED_CITIES: UsMetro[] = [
  {
    slug: "new-york-city",
    name: "New York City, NY",
    state: "NY",
    country: "US",
    lat: 40.71427,
    lng: -74.00597,
    radiusTier: "MEGA",
    aliases: [],
  },
  {
    slug: "toronto",
    name: "Toronto, ON",
    state: "ON",
    country: "CA",
    lat: 43.70643,
    lng: -79.39864,
    radiusTier: "MEGA",
    aliases: [],
  },
  {
    slug: "montreal",
    name: "Montréal, QC",
    state: "QC",
    country: "CA",
    lat: 45.50884,
    lng: -73.58781,
    radiusTier: "LARGE",
    aliases: [],
  },
  {
    slug: "calgary",
    name: "Calgary, AB",
    state: "AB",
    country: "CA",
    lat: 51.05011,
    lng: -114.08529,
    radiusTier: "LARGE",
    aliases: [],
  },
  {
    slug: "ottawa",
    name: "Ottawa, ON",
    state: "ON",
    country: "CA",
    lat: 45.41117,
    lng: -75.69812,
    radiusTier: "LARGE",
    aliases: [],
  },
  {
    slug: "edmonton",
    name: "Edmonton, AB",
    state: "AB",
    country: "CA",
    lat: 53.55014,
    lng: -113.46871,
    radiusTier: "LARGE",
    aliases: [],
  },
  {
    slug: "fort-worth",
    name: "Fort Worth, TX",
    state: "TX",
    country: "US",
    lat: 32.72541,
    lng: -97.32085,
    radiusTier: "LARGE",
    aliases: [],
  },
  {
    slug: "winnipeg",
    name: "Winnipeg, MB",
    state: "MB",
    country: "CA",
    lat: 49.8844,
    lng: -97.14704,
    radiusTier: "MID",
    aliases: [],
  },
  {
    slug: "mississauga",
    name: "Mississauga, ON",
    state: "ON",
    country: "CA",
    lat: 43.5789,
    lng: -79.6583,
    radiusTier: "MID",
    aliases: [],
  },
  {
    slug: "oklahoma-city",
    name: "Oklahoma City, OK",
    state: "OK",
    country: "US",
    lat: 35.46756,
    lng: -97.51643,
    radiusTier: "MID",
    aliases: [],
  },
  {
    slug: "el-paso",
    name: "El Paso, TX",
    state: "TX",
    country: "US",
    lat: 31.75872,
    lng: -106.48693,
    radiusTier: "MID",
    aliases: [],
  },
  {
    slug: "vancouver",
    name: "Vancouver, BC",
    state: "BC",
    country: "CA",
    lat: 49.24966,
    lng: -123.11934,
    radiusTier: "MID",
    aliases: [],
  },
  {
    slug: "brampton",
    name: "Brampton, ON",
    state: "ON",
    country: "CA",
    lat: 43.68341,
    lng: -79.76633,
    radiusTier: "MID",
    aliases: [],
  },
  {
    slug: "memphis",
    name: "Memphis, TN",
    state: "TN",
    country: "US",
    lat: 35.14953,
    lng: -90.04898,
    radiusTier: "MID",
    aliases: [],
  },
  {
    slug: "louisville",
    name: "Louisville, KY",
    state: "KY",
    country: "US",
    lat: 38.25424,
    lng: -85.75941,
    radiusTier: "MID",
    aliases: [],
  },
  {
    slug: "baltimore",
    name: "Baltimore, MD",
    state: "MD",
    country: "US",
    lat: 39.29038,
    lng: -76.61219,
    radiusTier: "MID",
    aliases: [],
  },
  {
    slug: "hamilton",
    name: "Hamilton, ON",
    state: "ON",
    country: "CA",
    lat: 43.25011,
    lng: -79.84963,
    radiusTier: "MID",
    aliases: [],
  },
  {
    slug: "surrey",
    name: "Surrey, BC",
    state: "BC",
    country: "CA",
    lat: 49.10635,
    lng: -122.82509,
    radiusTier: "MID",
    aliases: [],
  },
  {
    slug: "albuquerque",
    name: "Albuquerque, NM",
    state: "NM",
    country: "US",
    lat: 35.08449,
    lng: -106.65114,
    radiusTier: "MID",
    aliases: [],
  },
  {
    slug: "milwaukee",
    name: "Milwaukee, WI",
    state: "WI",
    country: "US",
    lat: 43.0389,
    lng: -87.90647,
    radiusTier: "MID",
    aliases: [],
  },
  {
    slug: "fresno",
    name: "Fresno, CA",
    state: "CA",
    country: "US",
    lat: 36.74773,
    lng: -119.77237,
    radiusTier: "MID",
    aliases: [],
  },
  {
    slug: "quebec",
    name: "Québec, QC",
    state: "QC",
    country: "CA",
    lat: 46.81228,
    lng: -71.21454,
    radiusTier: "MID",
    aliases: [],
  },
  {
    slug: "omaha",
    name: "Omaha, NE",
    state: "NE",
    country: "US",
    lat: 41.25626,
    lng: -95.94043,
    radiusTier: "MID",
    aliases: [],
  },
  {
    slug: "halifax",
    name: "Halifax, NS",
    state: "NS",
    country: "CA",
    lat: 44.64269,
    lng: -63.57688,
    radiusTier: "MID",
    aliases: [],
  },
  {
    slug: "staten-island",
    name: "Staten Island, NY",
    state: "NY",
    country: "US",
    lat: 40.56233,
    lng: -74.13986,
    radiusTier: "MID",
    aliases: [],
  },
  {
    slug: "colorado-springs",
    name: "Colorado Springs, CO",
    state: "CO",
    country: "US",
    lat: 38.83388,
    lng: -104.82136,
    radiusTier: "MID",
    aliases: [],
  },
  {
    slug: "virginia-beach",
    name: "Virginia Beach, VA",
    state: "VA",
    country: "US",
    lat: 36.85293,
    lng: -75.97799,
    radiusTier: "MID",
    aliases: [],
  },
  {
    slug: "laval",
    name: "Laval, QC",
    state: "QC",
    country: "CA",
    lat: 45.56995,
    lng: -73.692,
    radiusTier: "MID",
    aliases: [],
  },
  {
    slug: "london",
    name: "London, ON",
    state: "ON",
    country: "CA",
    lat: 42.98339,
    lng: -81.23304,
    radiusTier: "MID",
    aliases: [],
  },
  {
    slug: "tulsa",
    name: "Tulsa, OK",
    state: "OK",
    country: "US",
    lat: 36.15398,
    lng: -95.99277,
    radiusTier: "MID",
    aliases: [],
  },
  {
    slug: "wichita",
    name: "Wichita, KS",
    state: "KS",
    country: "US",
    lat: 37.69224,
    lng: -97.33754,
    radiusTier: "MID",
    aliases: [],
  },
  {
    slug: "arlington",
    name: "Arlington, TX",
    state: "TX",
    country: "US",
    lat: 32.73569,
    lng: -97.10807,
    radiusTier: "MID",
    aliases: [],
  },
  {
    slug: "bakersfield",
    name: "Bakersfield, CA",
    state: "CA",
    country: "US",
    lat: 35.37329,
    lng: -119.01871,
    radiusTier: "MID",
    aliases: [],
  },
  {
    slug: "cleveland",
    name: "Cleveland, OH",
    state: "OH",
    country: "US",
    lat: 41.4995,
    lng: -81.69541,
    radiusTier: "MID",
    aliases: [],
  },
  {
    slug: "etobicoke",
    name: "Etobicoke, ON",
    state: "ON",
    country: "CA",
    lat: 43.64415,
    lng: -79.56985,
    radiusTier: "MID",
    aliases: [],
  },
  {
    slug: "honolulu",
    name: "Honolulu, HI",
    state: "HI",
    country: "US",
    lat: 21.30694,
    lng: -157.85833,
    radiusTier: "MID",
    aliases: [],
  },
  {
    slug: "anaheim",
    name: "Anaheim, CA",
    state: "CA",
    country: "US",
    lat: 33.83529,
    lng: -117.9145,
    radiusTier: "MID",
    aliases: [],
  },
  {
    slug: "markham",
    name: "Markham, ON",
    state: "ON",
    country: "CA",
    lat: 43.86682,
    lng: -79.2663,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "vaughan",
    name: "Vaughan, ON",
    state: "ON",
    country: "CA",
    lat: 43.8361,
    lng: -79.49827,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "lexington",
    name: "Lexington, KY",
    state: "KY",
    country: "US",
    lat: 37.98869,
    lng: -84.47772,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "riverside",
    name: "Riverside, CA",
    state: "CA",
    country: "US",
    lat: 33.95335,
    lng: -117.39616,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "corpus-christi",
    name: "Corpus Christi, TX",
    state: "TX",
    country: "US",
    lat: 27.80058,
    lng: -97.39638,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "lexington-fayette",
    name: "Lexington-Fayette, KY",
    state: "KY",
    country: "US",
    lat: 38.0498,
    lng: -84.45855,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "cincinnati",
    name: "Cincinnati, OH",
    state: "OH",
    country: "US",
    lat: 39.12711,
    lng: -84.51439,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "santa-ana",
    name: "Santa Ana, CA",
    state: "CA",
    country: "US",
    lat: 33.74557,
    lng: -117.86783,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "stockton",
    name: "Stockton, CA",
    state: "CA",
    country: "US",
    lat: 37.9577,
    lng: -121.29078,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "pittsburgh",
    name: "Pittsburgh, PA",
    state: "PA",
    country: "US",
    lat: 40.44062,
    lng: -79.99589,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "gatineau",
    name: "Gatineau, QC",
    state: "QC",
    country: "CA",
    lat: 45.47723,
    lng: -75.70164,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "lincoln",
    name: "Lincoln, NE",
    state: "NE",
    country: "US",
    lat: 40.8,
    lng: -96.66696,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "victoria",
    name: "Victoria, BC",
    state: "BC",
    country: "CA",
    lat: 48.4359,
    lng: -123.35155,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "anchorage",
    name: "Anchorage, AK",
    state: "AK",
    country: "US",
    lat: 61.21806,
    lng: -149.90028,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "meads",
    name: "Meads, KY",
    state: "KY",
    country: "US",
    lat: 38.41258,
    lng: -82.70905,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "greensboro",
    name: "Greensboro, NC",
    state: "NC",
    country: "US",
    lat: 36.07264,
    lng: -79.79198,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "madison",
    name: "Madison, WI",
    state: "WI",
    country: "US",
    lat: 43.07305,
    lng: -89.40123,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "st-louis",
    name: "St. Louis, MO",
    state: "MO",
    country: "US",
    lat: 38.62727,
    lng: -90.19789,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "saskatoon",
    name: "Saskatoon, SK",
    state: "SK",
    country: "CA",
    lat: 52.13238,
    lng: -106.66892,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "toledo",
    name: "Toledo, OH",
    state: "OH",
    country: "US",
    lat: 41.66394,
    lng: -83.55521,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "reno",
    name: "Reno, NV",
    state: "NV",
    country: "US",
    lat: 39.52963,
    lng: -119.8138,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "fort-wayne",
    name: "Fort Wayne, IN",
    state: "IN",
    country: "US",
    lat: 41.1306,
    lng: -85.12886,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "buffalo",
    name: "Buffalo, NY",
    state: "NY",
    country: "US",
    lat: 42.88645,
    lng: -78.87837,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "irvine",
    name: "Irvine, CA",
    state: "CA",
    country: "US",
    lat: 33.66946,
    lng: -117.82311,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "kitchener",
    name: "Kitchener, ON",
    state: "ON",
    country: "CA",
    lat: 43.42537,
    lng: -80.5112,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "laredo",
    name: "Laredo, TX",
    state: "TX",
    country: "US",
    lat: 27.50641,
    lng: -99.50754,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "burnaby",
    name: "Burnaby, BC",
    state: "BC",
    country: "CA",
    lat: 49.26636,
    lng: -122.95263,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "lubbock",
    name: "Lubbock, TX",
    state: "TX",
    country: "US",
    lat: 33.57786,
    lng: -101.85517,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "tri-cities",
    name: "Tri-Cities, WA",
    state: "WA",
    country: "US",
    lat: 46.2454,
    lng: -119.19617,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "winston-salem",
    name: "Winston-Salem, NC",
    state: "NC",
    country: "US",
    lat: 36.09986,
    lng: -80.24422,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "norfolk",
    name: "Norfolk, VA",
    state: "VA",
    country: "US",
    lat: 36.84681,
    lng: -76.28522,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "boise",
    name: "Boise, ID",
    state: "ID",
    country: "US",
    lat: 43.6135,
    lng: -116.20345,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "chesapeake",
    name: "Chesapeake, VA",
    state: "VA",
    country: "US",
    lat: 36.81904,
    lng: -76.27494,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "fremont",
    name: "Fremont, CA",
    state: "CA",
    country: "US",
    lat: 37.54827,
    lng: -121.98857,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "windsor",
    name: "Windsor, ON",
    state: "ON",
    country: "CA",
    lat: 42.30008,
    lng: -83.01654,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "spokane",
    name: "Spokane, WA",
    state: "WA",
    country: "US",
    lat: 47.65966,
    lng: -117.42908,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "longueuil",
    name: "Longueuil, QC",
    state: "QC",
    country: "CA",
    lat: 45.5152,
    lng: -73.46818,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "baton-rouge",
    name: "Baton Rouge, LA",
    state: "LA",
    country: "US",
    lat: 30.44332,
    lng: -91.18747,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "richmond-va",
    name: "Richmond, VA",
    state: "VA",
    country: "US",
    lat: 37.55376,
    lng: -77.46026,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "regina",
    name: "Regina, SK",
    state: "SK",
    country: "CA",
    lat: 50.45008,
    lng: -104.6178,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "san-bernardino",
    name: "San Bernardino, CA",
    state: "CA",
    country: "US",
    lat: 34.10834,
    lng: -117.28977,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "huntsville",
    name: "Huntsville, AL",
    state: "AL",
    country: "US",
    lat: 34.7304,
    lng: -86.58594,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "des-moines",
    name: "Des Moines, IA",
    state: "IA",
    country: "US",
    lat: 41.60054,
    lng: -93.60911,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "oakville",
    name: "Oakville, ON",
    state: "ON",
    country: "CA",
    lat: 43.45011,
    lng: -79.68292,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "fontana",
    name: "Fontana, CA",
    state: "CA",
    country: "US",
    lat: 34.09223,
    lng: -117.43505,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "modesto",
    name: "Modesto, CA",
    state: "CA",
    country: "US",
    lat: 37.6391,
    lng: -120.99688,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "richmond",
    name: "Richmond, BC",
    state: "BC",
    country: "CA",
    lat: 49.17003,
    lng: -123.13683,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "rochester-ny",
    name: "Rochester, NY",
    state: "NY",
    country: "US",
    lat: 43.15478,
    lng: -77.61556,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "arlington-va",
    name: "Arlington, VA",
    state: "VA",
    country: "US",
    lat: 38.88101,
    lng: -77.10428,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "oxnard",
    name: "Oxnard, CA",
    state: "CA",
    country: "US",
    lat: 34.1975,
    lng: -119.17705,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "columbus-ga",
    name: "Columbus, GA",
    state: "GA",
    country: "US",
    lat: 32.46098,
    lng: -84.98771,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "worcester",
    name: "Worcester, MA",
    state: "MA",
    country: "US",
    lat: 42.26259,
    lng: -71.80229,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "moreno-valley",
    name: "Moreno Valley, CA",
    state: "CA",
    country: "US",
    lat: 33.93752,
    lng: -117.23059,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "little-rock",
    name: "Little Rock, AR",
    state: "AR",
    country: "US",
    lat: 34.74648,
    lng: -92.28959,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "richmond-hill",
    name: "Richmond Hill, ON",
    state: "ON",
    country: "CA",
    lat: 43.87111,
    lng: -79.43725,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "fayetteville",
    name: "Fayetteville, NC",
    state: "NC",
    country: "US",
    lat: 35.05266,
    lng: -78.87836,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "huntington-beach",
    name: "Huntington Beach, CA",
    state: "CA",
    country: "US",
    lat: 33.6603,
    lng: -117.99923,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "tallahassee",
    name: "Tallahassee, FL",
    state: "FL",
    country: "US",
    lat: 30.43826,
    lng: -84.28073,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "yonkers",
    name: "Yonkers, NY",
    state: "NY",
    country: "US",
    lat: 40.9304,
    lng: -73.89789,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "cypress",
    name: "Cypress, TX",
    state: "TX",
    country: "US",
    lat: 29.96911,
    lng: -95.69717,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "amarillo",
    name: "Amarillo, TX",
    state: "TX",
    country: "US",
    lat: 35.222,
    lng: -101.8313,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "akron",
    name: "Akron, OH",
    state: "OH",
    country: "US",
    lat: 41.08144,
    lng: -81.51901,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "vancouver-wa",
    name: "Vancouver, WA",
    state: "WA",
    country: "US",
    lat: 45.63873,
    lng: -122.66149,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "birmingham",
    name: "Birmingham, AL",
    state: "AL",
    country: "US",
    lat: 33.52066,
    lng: -86.80249,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "montgomery",
    name: "Montgomery, AL",
    state: "AL",
    country: "US",
    lat: 32.36681,
    lng: -86.29997,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "grand-rapids",
    name: "Grand Rapids, MI",
    state: "MI",
    country: "US",
    lat: 42.96336,
    lng: -85.66809,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "providence",
    name: "Providence, RI",
    state: "RI",
    country: "US",
    lat: 41.82399,
    lng: -71.41283,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "knoxville",
    name: "Knoxville, TN",
    state: "TN",
    country: "US",
    lat: 35.96064,
    lng: -83.92074,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "sunrise-manor",
    name: "Sunrise Manor, NV",
    state: "NV",
    country: "US",
    lat: 36.21108,
    lng: -115.07306,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "grand-prairie",
    name: "Grand Prairie, TX",
    state: "TX",
    country: "US",
    lat: 32.74596,
    lng: -96.99778,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "shreveport",
    name: "Shreveport, LA",
    state: "LA",
    country: "US",
    lat: 32.52515,
    lng: -93.75018,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "burlington",
    name: "Burlington, ON",
    state: "ON",
    country: "CA",
    lat: 43.38621,
    lng: -79.83713,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "brownsville",
    name: "Brownsville, TX",
    state: "TX",
    country: "US",
    lat: 25.90175,
    lng: -97.49748,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "newport-news",
    name: "Newport News, VA",
    state: "VA",
    country: "US",
    lat: 36.98038,
    lng: -76.42975,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "mobile",
    name: "Mobile, AL",
    state: "AL",
    country: "US",
    lat: 30.69436,
    lng: -88.04305,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "santa-clarita",
    name: "Santa Clarita, CA",
    state: "CA",
    country: "US",
    lat: 34.39166,
    lng: -118.54259,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "chattanooga",
    name: "Chattanooga, TN",
    state: "TN",
    country: "US",
    lat: 35.04563,
    lng: -85.30968,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "nepean",
    name: "Nepean, ON",
    state: "ON",
    country: "CA",
    lat: 45.33619,
    lng: -75.7225,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "spring-valley",
    name: "Spring Valley, NV",
    state: "NV",
    country: "US",
    lat: 36.10803,
    lng: -115.245,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "santa-rosa",
    name: "Santa Rosa, CA",
    state: "CA",
    country: "US",
    lat: 38.44047,
    lng: -122.71443,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "eugene",
    name: "Eugene, OR",
    state: "OR",
    country: "US",
    lat: 44.05207,
    lng: -123.08675,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "oceanside",
    name: "Oceanside, CA",
    state: "CA",
    country: "US",
    lat: 33.19587,
    lng: -117.37948,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "salem",
    name: "Salem, OR",
    state: "OR",
    country: "US",
    lat: 44.9429,
    lng: -123.0351,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "garden-grove",
    name: "Garden Grove, CA",
    state: "CA",
    country: "US",
    lat: 33.77391,
    lng: -117.94145,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "oshawa",
    name: "Oshawa, ON",
    state: "ON",
    country: "CA",
    lat: 43.90012,
    lng: -78.84957,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "rancho-cucamonga",
    name: "Rancho Cucamonga, CA",
    state: "CA",
    country: "US",
    lat: 34.1064,
    lng: -117.59311,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "cape-coral",
    name: "Cape Coral, FL",
    state: "FL",
    country: "US",
    lat: 26.56285,
    lng: -81.94953,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "sioux-falls",
    name: "Sioux Falls, SD",
    state: "SD",
    country: "US",
    lat: 43.54369,
    lng: -96.72796,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "ontario",
    name: "Ontario, CA",
    state: "CA",
    country: "US",
    lat: 34.06334,
    lng: -117.65089,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "fort-collins",
    name: "Fort Collins, CO",
    state: "CO",
    country: "US",
    lat: 40.58526,
    lng: -105.08442,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "springfield-mo",
    name: "Springfield, MO",
    state: "MO",
    country: "US",
    lat: 37.21533,
    lng: -93.29824,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "clarksville",
    name: "Clarksville, TN",
    state: "TN",
    country: "US",
    lat: 36.52977,
    lng: -87.35945,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "greater-sudbury",
    name: "Greater Sudbury, ON",
    state: "ON",
    country: "CA",
    lat: 46.49,
    lng: -80.99001,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "port-saint-lucie",
    name: "Port Saint Lucie, FL",
    state: "FL",
    country: "US",
    lat: 27.29393,
    lng: -80.35033,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "corona",
    name: "Corona, CA",
    state: "CA",
    country: "US",
    lat: 33.87529,
    lng: -117.56644,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "lancaster",
    name: "Lancaster, CA",
    state: "CA",
    country: "US",
    lat: 34.69804,
    lng: -118.13674,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "tempe-junction",
    name: "Tempe Junction, AZ",
    state: "AZ",
    country: "US",
    lat: 33.41421,
    lng: -111.94348,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "palmdale",
    name: "Palmdale, CA",
    state: "CA",
    country: "US",
    lat: 34.57943,
    lng: -118.11646,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "hayward",
    name: "Hayward, CA",
    state: "CA",
    country: "US",
    lat: 37.66882,
    lng: -122.0808,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "salinas",
    name: "Salinas, CA",
    state: "CA",
    country: "US",
    lat: 36.67774,
    lng: -121.6555,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "springfield-ma",
    name: "Springfield, MA",
    state: "MA",
    country: "US",
    lat: 42.10148,
    lng: -72.58981,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "east-chattanooga",
    name: "East Chattanooga, TN",
    state: "TN",
    country: "US",
    lat: 35.06535,
    lng: -85.24912,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "jackson",
    name: "Jackson, MS",
    state: "MS",
    country: "US",
    lat: 32.29876,
    lng: -90.18481,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "pomona",
    name: "Pomona, CA",
    state: "CA",
    country: "US",
    lat: 34.05529,
    lng: -117.75228,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "kansas-city-ks",
    name: "Kansas City, KS",
    state: "KS",
    country: "US",
    lat: 39.11417,
    lng: -94.62746,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "escondido",
    name: "Escondido, CA",
    state: "CA",
    country: "US",
    lat: 33.11921,
    lng: -117.08642,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "gloucester",
    name: "Gloucester, ON",
    state: "ON",
    country: "CA",
    lat: 45.35,
    lng: -75.63333,
    radiusTier: "SMALL",
    aliases: [],
  },
  {
    slug: "saguenay",
    name: "Saguenay, QC",
    state: "QC",
    country: "CA",
    lat: 48.41675,
    lng: -71.06573,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "coquitlam",
    name: "Coquitlam, BC",
    state: "BC",
    country: "CA",
    lat: 49.2846,
    lng: -122.78217,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "valencia",
    name: "Valencia, CA",
    state: "CA",
    country: "US",
    lat: 34.44361,
    lng: -118.60953,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "rockford",
    name: "Rockford, IL",
    state: "IL",
    country: "US",
    lat: 42.27113,
    lng: -89.094,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "east-hampton",
    name: "East Hampton, VA",
    state: "VA",
    country: "US",
    lat: 37.03737,
    lng: -76.33161,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "joliet",
    name: "Joliet, IL",
    state: "IL",
    country: "US",
    lat: 41.52519,
    lng: -88.0834,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "barrie",
    name: "Barrie, ON",
    state: "ON",
    country: "CA",
    lat: 44.40011,
    lng: -79.66634,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "savannah",
    name: "Savannah, GA",
    state: "GA",
    country: "US",
    lat: 32.08354,
    lng: -81.09983,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "paterson",
    name: "Paterson, NJ",
    state: "NJ",
    country: "US",
    lat: 40.91677,
    lng: -74.17181,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "bridgeport",
    name: "Bridgeport, CT",
    state: "CT",
    country: "US",
    lat: 41.17923,
    lng: -73.18945,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "rosemont-la-petite-patrie",
    name: "Rosemont–La Petite-Patrie, QC",
    state: "QC",
    country: "CA",
    lat: 45.53661,
    lng: -73.60686,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "gainesville",
    name: "Gainesville, FL",
    state: "FL",
    country: "US",
    lat: 29.65163,
    lng: -82.32483,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "villeray-saint-michel-parc-extension",
    name: "Villeray–Saint-Michel–Parc-Extension, QC",
    state: "QC",
    country: "CA",
    lat: 45.55869,
    lng: -73.60535,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "mesquite",
    name: "Mesquite, TX",
    state: "TX",
    country: "US",
    lat: 32.7668,
    lng: -96.59916,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "kelowna",
    name: "Kelowna, BC",
    state: "BC",
    country: "CA",
    lat: 49.88307,
    lng: -119.48568,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "trois-rivieres",
    name: "Trois-Rivières, QC",
    state: "QC",
    country: "CA",
    lat: 46.34515,
    lng: -72.5477,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "syracuse",
    name: "Syracuse, NY",
    state: "NY",
    country: "US",
    lat: 43.04812,
    lng: -76.14742,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "guelph",
    name: "Guelph, ON",
    state: "ON",
    country: "CA",
    lat: 43.54594,
    lng: -80.25599,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "torrance",
    name: "Torrance, CA",
    state: "CA",
    country: "US",
    lat: 33.83585,
    lng: -118.34063,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "levis",
    name: "Lévis, QC",
    state: "QC",
    country: "CA",
    lat: 46.80326,
    lng: -71.17793,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "surprise",
    name: "Surprise, AZ",
    state: "AZ",
    country: "US",
    lat: 33.63059,
    lng: -112.33322,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "mercier-hochelaga-maisonneuve",
    name: "Mercier–Hochelaga-Maisonneuve, QC",
    state: "QC",
    country: "CA",
    lat: 45.57194,
    lng: -73.54626,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "columbia-sc",
    name: "Columbia, SC",
    state: "SC",
    country: "US",
    lat: 34.00071,
    lng: -81.03481,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "abbotsford",
    name: "Abbotsford, BC",
    state: "BC",
    country: "CA",
    lat: 49.05798,
    lng: -122.25257,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "orange",
    name: "Orange, CA",
    state: "CA",
    country: "US",
    lat: 33.78779,
    lng: -117.85311,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "fullerton",
    name: "Fullerton, CA",
    state: "CA",
    country: "US",
    lat: 33.87029,
    lng: -117.92534,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "killeen",
    name: "Killeen, TX",
    state: "TX",
    country: "US",
    lat: 31.11712,
    lng: -97.7278,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "mcallen",
    name: "McAllen, TX",
    state: "TX",
    country: "US",
    lat: 26.20341,
    lng: -98.23001,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "whitby",
    name: "Whitby, ON",
    state: "ON",
    country: "CA",
    lat: 43.88342,
    lng: -78.93287,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "hampton",
    name: "Hampton, VA",
    state: "VA",
    country: "US",
    lat: 37.02987,
    lng: -76.34522,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "miramar",
    name: "Miramar, FL",
    state: "FL",
    country: "US",
    lat: 25.98731,
    lng: -80.23227,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "st-catharines",
    name: "St. Catharines, ON",
    state: "ON",
    country: "CA",
    lat: 43.17126,
    lng: -79.24267,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "dayton",
    name: "Dayton, OH",
    state: "OH",
    country: "US",
    lat: 39.75895,
    lng: -84.19161,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "warren",
    name: "Warren, MI",
    state: "MI",
    country: "US",
    lat: 42.49044,
    lng: -83.01304,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "thornton",
    name: "Thornton, CO",
    state: "CO",
    country: "US",
    lat: 39.86804,
    lng: -104.97192,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "carrollton",
    name: "Carrollton, TX",
    state: "TX",
    country: "US",
    lat: 32.95373,
    lng: -96.89028,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "milton",
    name: "Milton, ON",
    state: "ON",
    country: "CA",
    lat: 43.51681,
    lng: -79.88294,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "charleston",
    name: "Charleston, SC",
    state: "SC",
    country: "US",
    lat: 32.77632,
    lng: -79.93275,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "langley",
    name: "Langley, BC",
    state: "BC",
    country: "CA",
    lat: 49.10107,
    lng: -122.65883,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "midland",
    name: "Midland, TX",
    state: "TX",
    country: "US",
    lat: 31.99735,
    lng: -102.07791,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "kingston",
    name: "Kingston, ON",
    state: "ON",
    country: "CA",
    lat: 44.22976,
    lng: -76.48098,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "waco",
    name: "Waco, TX",
    state: "TX",
    country: "US",
    lat: 31.54933,
    lng: -97.14667,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "sterling-heights",
    name: "Sterling Heights, MI",
    state: "MI",
    country: "US",
    lat: 42.58031,
    lng: -83.0302,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "denton",
    name: "Denton, TX",
    state: "TX",
    country: "US",
    lat: 33.21484,
    lng: -97.13307,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "cedar-rapids",
    name: "Cedar Rapids, IA",
    state: "IA",
    country: "US",
    lat: 42.00833,
    lng: -91.64407,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "new-haven",
    name: "New Haven, CT",
    state: "CT",
    country: "US",
    lat: 41.30815,
    lng: -72.92816,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "visalia",
    name: "Visalia, CA",
    state: "CA",
    country: "US",
    lat: 36.33023,
    lng: -119.29206,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "sherbrooke",
    name: "Sherbrooke, QC",
    state: "QC",
    country: "CA",
    lat: 45.40008,
    lng: -71.89908,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "thousand-oaks",
    name: "Thousand Oaks, CA",
    state: "CA",
    country: "US",
    lat: 34.17056,
    lng: -118.83759,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "columbia",
    name: "Columbia, MO",
    state: "MO",
    country: "US",
    lat: 38.95171,
    lng: -92.33407,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "elizabeth",
    name: "Elizabeth, NJ",
    state: "NJ",
    country: "US",
    lat: 40.66399,
    lng: -74.2107,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "stamford",
    name: "Stamford, CT",
    state: "CT",
    country: "US",
    lat: 41.05343,
    lng: -73.53873,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "concord",
    name: "Concord, CA",
    state: "CA",
    country: "US",
    lat: 37.97798,
    lng: -122.03107,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "norman",
    name: "Norman, OK",
    state: "OK",
    country: "US",
    lat: 35.22257,
    lng: -97.43948,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "athens",
    name: "Athens, GA",
    state: "GA",
    country: "US",
    lat: 33.96095,
    lng: -83.37794,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "kent",
    name: "Kent, WA",
    state: "WA",
    country: "US",
    lat: 47.38093,
    lng: -122.23484,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "simi-valley",
    name: "Simi Valley, CA",
    state: "CA",
    country: "US",
    lat: 34.26945,
    lng: -118.78148,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "east-los-angeles",
    name: "East Los Angeles, CA",
    state: "CA",
    country: "US",
    lat: 34.0239,
    lng: -118.17202,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "topeka",
    name: "Topeka, KS",
    state: "KS",
    country: "US",
    lat: 39.04833,
    lng: -95.67804,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "orleans",
    name: "Orléans, ON",
    state: "ON",
    country: "CA",
    lat: 45.45732,
    lng: -75.50433,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "abilene",
    name: "Abilene, TX",
    state: "TX",
    country: "US",
    lat: 32.44874,
    lng: -99.73314,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "ottawa-south",
    name: "Ottawa South, ON",
    state: "ON",
    country: "CA",
    lat: 45.3921,
    lng: -75.68725,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "amherst",
    name: "Amherst, NY",
    state: "NY",
    country: "US",
    lat: 42.97839,
    lng: -78.79976,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "victorville",
    name: "Victorville, CA",
    state: "CA",
    country: "US",
    lat: 34.53611,
    lng: -117.29116,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "vallejo",
    name: "Vallejo, CA",
    state: "CA",
    country: "US",
    lat: 38.10409,
    lng: -122.25664,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "lafayette",
    name: "Lafayette, LA",
    state: "LA",
    country: "US",
    lat: 30.22409,
    lng: -92.01984,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "chico",
    name: "Chico, CA",
    state: "CA",
    country: "US",
    lat: 39.72849,
    lng: -121.83748,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "north-stamford",
    name: "North Stamford, CT",
    state: "CT",
    country: "US",
    lat: 41.13815,
    lng: -73.54346,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "hartford",
    name: "Hartford, CT",
    state: "CT",
    country: "US",
    lat: 41.76371,
    lng: -72.68509,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "west-palm-beach",
    name: "West Palm Beach, FL",
    state: "FL",
    country: "US",
    lat: 26.71534,
    lng: -80.05337,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "allentown",
    name: "Allentown, PA",
    state: "PA",
    country: "US",
    lat: 40.60843,
    lng: -75.49018,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "saint-louis-de-terrebonne",
    name: "Saint-Louis-de-Terrebonne, QC",
    state: "QC",
    country: "CA",
    lat: 45.70198,
    lng: -73.78669,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "evansville",
    name: "Evansville, IN",
    state: "IN",
    country: "US",
    lat: 37.97476,
    lng: -87.55585,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "palm-bay",
    name: "Palm Bay, FL",
    state: "FL",
    country: "US",
    lat: 28.03446,
    lng: -80.58866,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "ajax",
    name: "Ajax, ON",
    state: "ON",
    country: "CA",
    lat: 43.85012,
    lng: -79.03288,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "fargo",
    name: "Fargo, ND",
    state: "ND",
    country: "US",
    lat: 46.87719,
    lng: -96.7898,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "saanich",
    name: "Saanich, BC",
    state: "BC",
    country: "CA",
    lat: 48.54964,
    lng: -123.36931,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "independence",
    name: "Independence, MO",
    state: "MO",
    country: "US",
    lat: 39.09112,
    lng: -94.41551,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "billings",
    name: "Billings, MT",
    state: "MT",
    country: "US",
    lat: 45.78329,
    lng: -108.50069,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "ann-arbor",
    name: "Ann Arbor, MI",
    state: "MI",
    country: "US",
    lat: 42.27756,
    lng: -83.74088,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "el-monte",
    name: "El Monte, CA",
    state: "CA",
    country: "US",
    lat: 34.06862,
    lng: -118.02757,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "westminster",
    name: "Westminster, CO",
    state: "CO",
    country: "US",
    lat: 39.83665,
    lng: -105.0372,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "wilmington",
    name: "Wilmington, NC",
    state: "NC",
    country: "US",
    lat: 34.23556,
    lng: -77.94604,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "arvada",
    name: "Arvada, CO",
    state: "CO",
    country: "US",
    lat: 39.80276,
    lng: -105.08748,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "beaumont",
    name: "Beaumont, TX",
    state: "TX",
    country: "US",
    lat: 30.08605,
    lng: -94.10185,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "odessa",
    name: "Odessa, TX",
    state: "TX",
    country: "US",
    lat: 31.84568,
    lng: -102.36764,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "springfield",
    name: "Springfield, IL",
    state: "IL",
    country: "US",
    lat: 39.80172,
    lng: -89.64371,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "downey",
    name: "Downey, CA",
    state: "CA",
    country: "US",
    lat: 33.94001,
    lng: -118.13257,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "riviere-des-prairies-pointe-aux-trembles",
    name: "Rivière-des-Prairies–Pointe-aux-Trembles, QC",
    state: "QC",
    country: "CA",
    lat: 45.64064,
    lng: -73.58463,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "costa-mesa",
    name: "Costa Mesa, CA",
    state: "CA",
    country: "US",
    lat: 33.64113,
    lng: -117.91867,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "north-peoria",
    name: "North Peoria, IL",
    state: "IL",
    country: "US",
    lat: 40.71754,
    lng: -89.58426,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "fairfield",
    name: "Fairfield, CA",
    state: "CA",
    country: "US",
    lat: 38.24936,
    lng: -122.03997,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "lansing",
    name: "Lansing, MI",
    state: "MI",
    country: "US",
    lat: 42.73253,
    lng: -84.55553,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "rochester",
    name: "Rochester, MN",
    state: "MN",
    country: "US",
    lat: 44.02163,
    lng: -92.4699,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "elgin",
    name: "Elgin, IL",
    state: "IL",
    country: "US",
    lat: 42.03725,
    lng: -88.28119,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "west-jordan",
    name: "West Jordan, UT",
    state: "UT",
    country: "US",
    lat: 40.60967,
    lng: -111.9391,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "inglewood",
    name: "Inglewood, CA",
    state: "CA",
    country: "US",
    lat: 33.96168,
    lng: -118.35313,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "terrebonne",
    name: "Terrebonne, QC",
    state: "QC",
    country: "CA",
    lat: 45.70004,
    lng: -73.64732,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "tuscaloosa",
    name: "Tuscaloosa, AL",
    state: "AL",
    country: "US",
    lat: 33.20984,
    lng: -87.56917,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "lowell",
    name: "Lowell, MA",
    state: "MA",
    country: "US",
    lat: 42.63342,
    lng: -71.31617,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "antioch",
    name: "Antioch, CA",
    state: "CA",
    country: "US",
    lat: 38.00492,
    lng: -121.80579,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "st-john-s",
    name: "St. John's, NL",
    state: "NL",
    country: "CA",
    lat: 47.56494,
    lng: -52.70931,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "high-point",
    name: "High Point, NC",
    state: "NC",
    country: "US",
    lat: 35.95569,
    lng: -80.00532,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "manchester",
    name: "Manchester, NH",
    state: "NH",
    country: "US",
    lat: 42.99564,
    lng: -71.45479,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "temecula",
    name: "Temecula, CA",
    state: "CA",
    country: "US",
    lat: 33.49364,
    lng: -117.14836,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "murrieta",
    name: "Murrieta, CA",
    state: "CA",
    country: "US",
    lat: 33.55391,
    lng: -117.21392,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "richmond-ca",
    name: "Richmond, CA",
    state: "CA",
    country: "US",
    lat: 37.93576,
    lng: -122.34775,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "pueblo",
    name: "Pueblo, CO",
    state: "CO",
    country: "US",
    lat: 38.25445,
    lng: -104.60914,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "thunder-bay",
    name: "Thunder Bay, ON",
    state: "ON",
    country: "CA",
    lat: 48.38202,
    lng: -89.25018,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "waterbury",
    name: "Waterbury, CT",
    state: "CT",
    country: "US",
    lat: 41.55815,
    lng: -73.0515,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "greeley",
    name: "Greeley, CO",
    state: "CO",
    country: "US",
    lat: 40.42331,
    lng: -104.70913,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "west-covina",
    name: "West Covina, CA",
    state: "CA",
    country: "US",
    lat: 34.06862,
    lng: -117.93895,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "enterprise",
    name: "Enterprise, NV",
    state: "NV",
    country: "US",
    lat: 36.02525,
    lng: -115.24194,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "north-charleston",
    name: "North Charleston, SC",
    state: "SC",
    country: "US",
    lat: 32.85462,
    lng: -79.97481,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "college-station",
    name: "College Station, TX",
    state: "TX",
    country: "US",
    lat: 30.62798,
    lng: -96.33441,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "south-fulton",
    name: "South Fulton, GA",
    state: "GA",
    country: "US",
    lat: 33.59259,
    lng: -84.67294,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "norwalk",
    name: "Norwalk, CA",
    state: "CA",
    country: "US",
    lat: 33.90224,
    lng: -118.08173,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "broken-arrow",
    name: "Broken Arrow, OK",
    state: "OK",
    country: "US",
    lat: 36.0526,
    lng: -95.79082,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "sydney",
    name: "Sydney, NS",
    state: "NS",
    country: "CA",
    lat: 46.1351,
    lng: -60.1831,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "le-plateau-mont-royal",
    name: "Le Plateau-Mont-Royal, QC",
    state: "QC",
    country: "CA",
    lat: 45.52833,
    lng: -73.58081,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "green-bay",
    name: "Green Bay, WI",
    state: "WI",
    country: "US",
    lat: 44.51916,
    lng: -88.01983,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "santa-maria",
    name: "Santa Maria, CA",
    state: "CA",
    country: "US",
    lat: 34.95303,
    lng: -120.43572,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "waterloo",
    name: "Waterloo, ON",
    state: "ON",
    country: "CA",
    lat: 43.4668,
    lng: -80.51639,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "ville-marie",
    name: "Ville-Marie, QC",
    state: "QC",
    country: "CA",
    lat: 45.49899,
    lng: -73.57046,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "wichita-falls",
    name: "Wichita Falls, TX",
    state: "TX",
    country: "US",
    lat: 33.91371,
    lng: -98.49339,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "brantford",
    name: "Brantford, ON",
    state: "ON",
    country: "CA",
    lat: 43.1334,
    lng: -80.26636,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "kamloops",
    name: "Kamloops, BC",
    state: "BC",
    country: "CA",
    lat: 50.66648,
    lng: -120.3192,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "lakeland",
    name: "Lakeland, FL",
    state: "FL",
    country: "US",
    lat: 28.03947,
    lng: -81.9498,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "clovis",
    name: "Clovis, CA",
    state: "CA",
    country: "US",
    lat: 36.82523,
    lng: -119.70292,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "lewisville",
    name: "Lewisville, TX",
    state: "TX",
    country: "US",
    lat: 33.04623,
    lng: -96.99417,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "tyler",
    name: "Tyler, TX",
    state: "TX",
    country: "US",
    lat: 32.35126,
    lng: -95.30106,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "el-cajon",
    name: "El Cajon, CA",
    state: "CA",
    country: "US",
    lat: 32.79477,
    lng: -116.96253,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "san-mateo",
    name: "San Mateo, CA",
    state: "CA",
    country: "US",
    lat: 37.56299,
    lng: -122.32553,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "lethbridge",
    name: "Lethbridge, AB",
    state: "AB",
    country: "CA",
    lat: 49.69999,
    lng: -112.81856,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "rialto",
    name: "Rialto, CA",
    state: "CA",
    country: "US",
    lat: 34.1064,
    lng: -117.37032,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "davenport",
    name: "Davenport, IA",
    state: "IA",
    country: "US",
    lat: 41.52364,
    lng: -90.57764,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "edison",
    name: "Edison, NJ",
    state: "NJ",
    country: "US",
    lat: 40.51872,
    lng: -74.4121,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "delta",
    name: "Delta, BC",
    state: "BC",
    country: "CA",
    lat: 49.08917,
    lng: -123.05322,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "las-cruces",
    name: "Las Cruces, NM",
    state: "NM",
    country: "US",
    lat: 32.31232,
    lng: -106.77834,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "south-bend",
    name: "South Bend, IN",
    state: "IN",
    country: "US",
    lat: 41.68338,
    lng: -86.25001,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "chilliwack",
    name: "Chilliwack, BC",
    state: "BC",
    country: "CA",
    lat: 49.16638,
    lng: -121.95257,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "dartmouth",
    name: "Dartmouth, NS",
    state: "NS",
    country: "CA",
    lat: 44.67134,
    lng: -63.57719,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "albany",
    name: "Albany, NY",
    state: "NY",
    country: "US",
    lat: 42.65258,
    lng: -73.75623,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "new-bedford",
    name: "New Bedford, MA",
    state: "MA",
    country: "US",
    lat: 41.63526,
    lng: -70.92701,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "vista",
    name: "Vista, CA",
    state: "CA",
    country: "US",
    lat: 33.20004,
    lng: -117.24254,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "red-deer",
    name: "Red Deer, AB",
    state: "AB",
    country: "CA",
    lat: 52.26682,
    lng: -113.802,
    radiusTier: "MICRO",
    aliases: [],
  },
  {
    slug: "roanoke",
    name: "Roanoke, VA",
    state: "VA",
    country: "US",
    lat: 37.27097,
    lng: -79.94143,
    radiusTier: "MICRO",
    aliases: [],
  },
];
