ALTER TABLE "LighthouseAudit" ADD COLUMN IF NOT EXISTS "desktopPerformance" DOUBLE PRECISION;
ALTER TABLE "LighthouseAudit" ADD COLUMN IF NOT EXISTS "desktopLcp" DOUBLE PRECISION;
ALTER TABLE "LighthouseAudit" ADD COLUMN IF NOT EXISTS "desktopInp" DOUBLE PRECISION;
ALTER TABLE "LighthouseAudit" ADD COLUMN IF NOT EXISTS "desktopCls" DOUBLE PRECISION;
